import os
import re
import pandas as pd
from typing import List, Dict, Optional
import sqlite3


class BaseAnnotator:
    """Base class for taxonomic annotators.
    
    This class provides a unified interface for generating execution commands 
    for Snakemake and parsing the resulting output files into a standardized format.
    """
    
    def __init__(self, run_config: Dict, config: Dict):
        """Initialize the annotator with run-specific and global configurations.
        
        Args:
            run_config: Dictionary containing settings for this specific run 
                        (e.g., db_path, threads, extra flags).
            config: The global Snakemake configuration dictionary.
        """
        self.run_config = run_config
        self.config = config
        
        # Extract common parameters shared across all annotation tools
        self.run_name = run_config.get("run_name", "unknown_run")
        self.db_path = run_config.get("db_path", "")
        self.threads = run_config.get("threads", 1)
        self.extra = run_config.get("extra", "")
        
        # Use custom command if provided in config, otherwise fall back to the tool's default
        self.cmd = run_config.get("cmd", self.default_cmd)


    @property
    def default_cmd(self) -> str:
        """Get the default shell command for the tool.
        
        This property must be overridden in child classes (e.g., returning 'kraken2').
        
        Returns:
            String representing the default base command.
        """
        raise NotImplementedError("Method default_cmd must be implemented in child class")


    def get_expected_outputs(self, sample: str, output_dir: str) -> List[str]:
        """Generate a list of expected output files for a given sample.
        
        Args:
            sample: The sample ID (e.g., 'sample_1').
            output_dir: The directory where output files should be saved.
            
        Returns:
            List of absolute or relative paths to the expected output files.
        """
        raise NotImplementedError("Method get_expected_outputs must be implemented in child class")


    def get_snakemake_shell_cmd(self, input_r1: str, input_r2: str, outputs: List[str]) -> str:
        """Generate the bash command string to be executed by Snakemake.
        
        Args:
            input_r1: Path to the forward reads (R1) FASTQ file.
            input_r2: Path to the reverse reads (R2) FASTQ file.
            outputs: List of output file paths (generated by get_expected_outputs).
            
        Returns:
            A formatted bash command string.
        """
        raise NotImplementedError("Method get_snakemake_shell_cmd must be implemented in child class")


    def parse_output(self, file_path: str) -> pd.DataFrame:
        """Parse the raw tool output into a standardized pandas DataFrame.
        
        Args:
            file_path: Path to the raw output file generated by the tool.
            
        Returns:
            A pandas DataFrame strictly containing two columns: ['seq', 'taxID'].
        """
        raise NotImplementedError("Method parse_output must be implemented in child class")
    

class Kraken2Annotator(BaseAnnotator):
    """Annotator class for Kraken2 taxonomic classifier.
    
    Handles the generation of execution commands and parses the specific 
    five-column tabular output produced by Kraken2.
    """
    
    @property
    def default_cmd(self) -> str:
        """Return the default command to invoke Kraken2."""
        return "kraken2"


    def get_expected_outputs(self, sample: str, output_dir: str) -> List[str]:
        """Define the files Kraken2 is expected to generate.
        
        Kraken2 generates a detailed report file and a read-by-read output file. 
        We need both for the pipeline.
        """
        report_file = os.path.join(output_dir, f"{sample}_{self.run_name}.kraken2.report")
        out_file = os.path.join(output_dir, f"{sample}_{self.run_name}.kraken2.out")
        return [report_file, out_file]


    def get_snakemake_shell_cmd(self, input_r1: str, input_r2: str, outputs: List[str]) -> str:
        """Construct the shell command for Snakemake."""
        # Unpack the outputs list generated by get_expected_outputs
        report_file, out_file = outputs
        
        # Build the command using f-strings for readability
        cmd = (
            f"{self.cmd} "
            f"--use-names "
            f"--db {self.db_path} "
            f"--threads {self.threads} "
            f"--paired {input_r1} {input_r2} "
            f"--report {report_file} "
            f"--output {out_file} "
            f"{self.extra}"
        )
        return cmd

    def parse_output(self, file_path: str) -> pd.DataFrame:
        """Parse the Kraken2 read-by-read output file.
        
        Extracts the sequence ID and the NCBI taxID from the raw text.
        """
        # Read the raw TSV file without headers
        df = pd.read_table(file_path, header=None)
        
        # Assign temporary column names based on Kraken2 standard output
        df.columns = ["classified", "seq", "taxa", "length", "k-mer"]
        
        # Extract the numeric taxID from the 'taxa' column string
        def extract_taxid(taxa_string):
            if pd.isna(taxa_string):
                return "0"
            
            # Regex looks for numbers immediately following the word "taxid "
            match = re.search(r'(?<=taxid )[0-9]*', str(taxa_string))
            return match.group(0) if match else "0"
            
        df["taxID"] = df["taxa"].apply(extract_taxid)
        
        # Return only the columns required by SamovaR
        return df[["seq", "taxID"]]
    

class KaijuAnnotator(BaseAnnotator):
    """Annotator class for Kaiju taxonomic classifier.
    
    Handles the specific database flags (-t, -f) and parses 
    the standard 3-column output of Kaiju.
    """
    
    @property
    def default_cmd(self) -> str:
        """Return the default command to invoke Kaiju."""
        return "kaiju"


    def get_expected_outputs(self, sample: str, output_dir: str) -> List[str]:
        """Define the files Kaiju is expected to generate.
        
        Unlike Kraken2, Kaiju typically generates only one main output file.
        """
        out_file = os.path.join(output_dir, f"{sample}_{self.run_name}.kaiju.out")
        return [out_file]
    

    def get_snakemake_shell_cmd(self, input_r1: str, input_r2: str, outputs: List[str]) -> str:
        """Construct the shell command for Snakemake specifically for Kaiju."""
        
        # Extract the single expected output file from the list
        out_file = outputs[0]
        
        # Logic for finding the database index file (.fmi)
        # Migrated from the legacy get_db_file() function
        if self.run_config.get('db_name'):
            db_file_path = os.path.join(self.db_path, self.run_config['db_name'])
        elif self.db_path.endswith('.fmi'):
            db_file_path = self.db_path
        else:
            # If only a directory is provided, append a wildcard to find the .fmi file
            db_file_path = os.path.join(self.db_path, "*.fmi")
            
        # Logic for finding the taxonomy nodes file (nodes.dmp)
        default_nodes = os.path.join(os.path.dirname(db_file_path), "nodes.dmp")
        db_nodes = self.run_config.get('db_nodes', default_nodes)

        # Assemble the command string using specific Kaiju flags
        cmd = (
            f"{self.cmd} "
            f"-t {db_nodes} "
            f"-f {db_file_path} "
            f"-i {input_r1} "
            f"-j {input_r2} "
            f"-z {self.threads} "
            f"-o {out_file} "
            f"{self.extra}"
        )
        return cmd

    def parse_output(self, file_path: str) -> pd.DataFrame:
        """Parse the raw Kaiju output file.
        
        Kaiju produces a simple tab-separated format: 
        classification status (C/U), sequence ID, and NCBI taxID.
        No complex regular expressions are required for parsing.
        """
        # Read the TSV file without headers
        df = pd.read_table(file_path, header=None)
        
        # Assign standard column names
        df.columns = ["classified", "seq", "taxID"]
        
        # Return strictly the two columns required by the BaseAnnotator contract
        return df[["seq", "taxID"]]
    

class MetaPhlanAnnotator(BaseAnnotator):
    """Annotator class for the MetaPhlAn taxonomic classifier.
    
    Handles the execution of MetaPhlAn, post-processing of Bowtie2 output,
    and ID translation via SQLite.
    """

    @property
    def default_cmd(self) -> str:
        """Return the default command to invoke MetaPhlAn."""
        return "metaphlan"

    def get_expected_outputs(self, sample: str, output_dir: str) -> List[str]:
        """Define the list of files MetaPhlAn generates.
        
        Includes the final text output, the raw log, and the compressed Bowtie2 mapping.
        """
        out_file = os.path.join(output_dir, f"{sample}_{self.run_name}.metaphlan4.out")
        raw_file = os.path.join(output_dir, f"{sample}_{self.run_name}.metaphlan4.raw")
        bowtie_file = os.path.join(output_dir, f"{sample}_{self.run_name}.bowtie2.bz2")
        
        # We return them in a specific order so we can easily unpack them later
        return [out_file, raw_file, bowtie_file]

    def get_snakemake_shell_cmd(self, input_r1: str, input_r2: str, outputs: List[str]) -> str:
        """Construct the shell command, including the awk post-processing step."""
        # Unpack the list of outputs strictly in the order they were returned above
        out_file, raw_file, bowtie_file = outputs
        
        # Construct the command chaining MetaPhlAn execution and bash text processing
        cmd = (
            f"{self.cmd} "
            f"--input_type fastq "
            f"--nproc {self.threads} "
            f"-1 {input_r1} "
            f"-2 {input_r2} "
            f"--bowtie2out {bowtie_file} "
            f"-o {raw_file} "
            f"{self.extra} "
            f"&& "
            f"bzcat {bowtie_file} | awk -F'\\t' '{{print $1 \"\\t\" $3}}' > {out_file}"
        )
        return cmd
    

    def _get_db_mapping(self) -> Dict[str, str]:
        """Parse the MetaPhlAn SQLite database to retrieve ID mappings.
        
        MetaPhlAn often outputs internal reference IDs (e.g., 'M123-c456') 
        instead of standard NCBI taxIDs. This private method accesses the 
        tool's built-in SQLite database to build a translation dictionary.
        
        Returns:
            A dictionary mapping internal reference IDs to standard NCBI taxIDs.
            Returns an empty dictionary if the database cannot be found.
        """
        # Check if the database path is provided and the file exists
        if not self.db_path:
            return {}
            
        db_file = os.path.join(self.db_path, "mpa_v30_CHOCOPhlAn_201901_species_map.db")
        if not os.path.exists(db_file):
            return {}
            
        # Connect to the SQLite database
        conn = sqlite3.connect(db_file)
        cursor = conn.cursor()
        
        # Execute SQL query to fetch the mapping table
        cursor.execute("SELECT ref_id, tax_id FROM mpa_species_map")
        
        # Build the translation dictionary using dictionary comprehension
        mapping = {str(row[0]): str(row[1]) for row in cursor.fetchall()}
        
        # Always close the connection to avoid locking the database
        conn.close()
        
        return mapping

    def parse_output(self, file_path: str) -> pd.DataFrame:
        """Parse the processed MetaPhlAn output and standardize taxIDs.
        
        Reads the 2-column TSV generated by the post-processing awk command,
        extracts the internal reference IDs, and translates them to NCBI taxIDs.
        
        Args:
            file_path: Path to the processed '.out' file.
            
        Returns:
            A standardized pandas DataFrame containing ['seq', 'taxID'] columns.
        """
        # Read the output file generated by our awk command in the shell
        df = pd.read_table(file_path, header=None)
        df.columns = ["seq", "taxID"]
        
        # Retrieve the mapping dictionary
        db_mapping = self._get_db_mapping()
        
        if db_mapping:
            def extract_ref_id(tax_string: str) -> Optional[str]:
                """Extract the specific MetaPhlAn reference pattern from a string."""
                if pd.isna(tax_string):
                    return None
                
                # Search for the pattern: 'M' followed by digits, '-c', and more digits
                match = re.search(r'M\d+-c\d+', str(tax_string))
                return match.group(0) if match else None

            # Extract the internal ID into a temporary column
            df["ref_id"] = df["taxID"].apply(extract_ref_id)
            
            # Translate internal IDs to NCBI taxIDs. 
            # If an ID is not found in the mapping, replace it with "0" (unclassified).
            df["taxID"] = df["ref_id"].map(db_mapping).fillna("0")
            
            # Drop the temporary column to keep the DataFrame clean
            df = df.drop(columns=["ref_id"])
            
        # Return the standard 2-column format
        return df[["seq", "taxID"]]
    

class Kraken1Annotator(BaseAnnotator):
    """Annotator class for the original Kraken (Kraken 1) classifier.
    
    Generates execution commands for Kraken 1 and parses its standard 
    5-column tabular output.
    """

    @property
    def default_cmd(self) -> str:
        """Return the default command to invoke Kraken 1."""
        return "kraken"

    def get_expected_outputs(self, sample: str, output_dir: str) -> List[str]:
        """Define the expected output file for Kraken 1."""
        out_file = os.path.join(output_dir, f"{sample}_{self.run_name}.kraken.out")
        return [out_file]

    def get_snakemake_shell_cmd(self, input_r1: str, input_r2: str, outputs: List[str]) -> str:
        """Construct the shell command for Snakemake."""
        out_file = outputs[0]
        
        cmd = (
            f"{self.cmd} "
            f"--db {self.db_path} "
            f"--threads {self.threads} "
            f"--paired {input_r1} {input_r2} "
            f"--output {out_file} "
            f"{self.extra}"
        )
        return cmd

    def parse_output(self, file_path: str) -> pd.DataFrame:
        """Parse the Kraken 1 output file.
        Kraken 1 outputs the pure taxID in the 3rd column, 
        so no regular expressions are required.
        """
        df = pd.read_table(file_path, header=None)
        df.columns = ["classified", "seq", "taxID", "length", "k-mer"]
        return df[["seq", "taxID"]]


class KrakenUniqAnnotator(BaseAnnotator):
    """Annotator class for the KrakenUniq taxonomic classifier."""

    @property
    def default_cmd(self) -> str:
        """Return the default command to invoke KrakenUniq."""
        return "krakenuniq"

    def get_expected_outputs(self, sample: str, output_dir: str) -> List[str]:
        """Define the expected output file for KrakenUniq."""
        out_file = os.path.join(output_dir, f"{sample}_{self.run_name}.krakenuniq.out")
        return [out_file]

    def get_snakemake_shell_cmd(self, input_r1: str, input_r2: str, outputs: List[str]) -> str:
        """Construct the shell command for Snakemake."""
        out_file = outputs[0]
        
        cmd = (
            f"{self.cmd} "
            f"--db {self.db_path} "
            f"--threads {self.threads} "
            f"--paired {input_r1} {input_r2} "
            f"--output {out_file} "
            f"{self.extra}"
        )
        return cmd

    def parse_output(self, file_path: str) -> pd.DataFrame:
        """Parse the KrakenUniq output file.
        
        The output format is identical to Kraken 1.
        """
        df = pd.read_table(file_path, header=None)
        df.columns = ["classified", "seq", "taxID", "length", "k-mer"]
        return df[["seq", "taxID"]]
    

class CustomAnnotator(BaseAnnotator):
    """Annotator class for user-defined custom classification tools.
    
    This class acts as a universal wrapper. It expects a bash script that 
    strictly follows a defined API using command-line flags (-i, -I, -d, -o, -p) 
    and outputs a 2-column TSV file (sequence_id, taxID).
    """

    @property
    def default_cmd(self) -> str:
        """Return the default command to invoke the custom script.
        
        This can be overridden in the run_config via the 'cmd' key.
        """
        return "bash src/annotators/custom.sh"

    def get_expected_outputs(self, sample: str, output_dir: str) -> List[str]:
        """Define the expected output file for the custom tool."""
        out_file = os.path.join(output_dir, f"{sample}_{self.run_name}.custom.out")
        return [out_file]

    def get_snakemake_shell_cmd(self, input_r1: str, input_r2: str, outputs: List[str]) -> str:
        """Construct the shell command using the standardized custom API flags."""
        out_file = outputs[0]
        
        cmd = (
            f"{self.cmd} "
            f"-i {input_r1} "
            f"-I {input_r2} "
            f"-d {self.db_path} "
            f"-o {out_file} "
            f"-p \"{self.extra}\""
        )
        return cmd

    def parse_output(self, file_path: str) -> pd.DataFrame:
        """Parse the output of the custom tool.
        
        Since the custom bash script is required to output a clean, 
        2-column TSV file (seq, taxID), the parsing is straightforward.
        """
        df = pd.read_table(file_path, header=None)
        
        # In case the custom script outputs more columns by accident,
        # we strictly take only the first two.
        df = df.iloc[:, [0, 1]]
        
        df.columns = ["seq", "taxID"]
        
        return df
        

def get_annotator_instance(tool_type: str, run_config: Dict, config: Dict) -> BaseAnnotator:
    """Factory function to instantiate the correct annotator class.
    
    Args:
        tool_type: A string identifying the tool (e.g., 'kraken2', 'custom').
        run_config: The dictionary containing specific run settings.
        config: The global configuration dictionary.
        
    Returns:
        An instantiated object of a subclass of BaseAnnotator.
    """
    # Normalize the string to avoid case/alias mismatches
    tool = tool_type.lower()
    
    if tool in ["kraken2"]:
        return Kraken2Annotator(run_config, config)
    elif tool in ["kaiju"]:
        return KaijuAnnotator(run_config, config)
    elif tool in ["metaphlan", "metaphlan4", "mpa", "mp4"]:
        return MetaPhlanAnnotator(run_config, config)
    elif tool in ["kraken", "kraken1"]:
        return Kraken1Annotator(run_config, config)
    elif tool in ["krakenuniq", "krakenu"]:
        return KrakenUniqAnnotator(run_config, config)
    elif tool in ["custom"]:
        return CustomAnnotator(run_config, config)
    else:
        raise ValueError(f"Unknown annotator type requested: {tool_type}")
        
    